apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-central1-docker.pkg.dev/proud-research-428901-i9/kub-assignment-repo/container2
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: data-volume
              mountPath: /app/MEER_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: persistent-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: c2-service
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
